image: node:12.22.6

cache:
  paths:
    - node_modules/

stages:
  # - Preparation
  - Build
  # - Deploy

# Preparation-job:
#   stage: Preparation
#   script:
#   - npm i

Build-job:
  stage: Build
  script:
  - npm run build
  - pwd
  - ls -a
  - cd app
  - ls -a

# Deploy-job:
#   stage: Deploy
#   script:
#   - pwd
#   - ls -a
  # - npm run stop
  # - npm run start
