image: node:12.22.6

# cache:
#   paths:
#     - node_modules/

stages:
  # - Preparation
  # - Build
  - Deploy

# Preparation:
#   stage: Preparation
#   script:
#   - npm i

# Build:
#   stage: Build
#   script:
#   - npm run build

Deploy:
  stage: Deploy
  script:
  # - npm run stop
  # - npm run start
  - sh deploy.sh ${USER} ${IP} ${PASSWORD}
